name       : ksysguard
version    : 5.20.4
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/ksysguard-5.20.4.tar.xz : a5f247b24ce75a28f301446fbeb25abf968e77e0c32cd4be9b574a21d3bbfaf4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Monitor various elements of your system
libsplit   : no
description: |
    KSysGuard is a program to monitor various elements of your system, or any other remote system with the KSysGuard daemon.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(libcap)
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnm)
    - pkgconfig(libpcap)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - networkmanager-qt-devel
    - knewstuff-devel
    - knotifications-devel
    - kwindowsystem-devel
    - libksysguard-devel
    - lm_sensors-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-defaults-path.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
