name       : ksysguard
version    : 5.16.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/ksysguard-5.16.0.tar.xz : bf902d3f4f3410bd5dce1c647599625b296859dc1a5dd9ccd694ff5e77e11256
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Monitor various elements of your system
description: |
    KSysGuard is a program to monitor various elements of your system, or any other remote system with the KSysGuard daemon.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - kitemviews-devel
    - knewstuff-devel
    - knotifications-devel
    - kwindowsystem-devel
    - libksysguard-devel
    - lm_sensors-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-Solus-defaults-path.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
